2020-11-18 22:10:56
打印异常日志：
Traceback (most recent call last):
  File "D:/python/studentInfor/geneTonjiCard.py", line 293, in <module>
    doc.save(fileName)
  File "D:\Program Files (x86)\python\lib\site-packages\docxtpl\__init__.py", line 632, in save
    self.docx.save(filename, *args, **kwargs)
  File "D:\Program Files (x86)\python\lib\site-packages\docx\document.py", line 135, in save
    self._part.save(path_or_stream)
  File "D:\Program Files (x86)\python\lib\site-packages\docx\parts\document.py", line 111, in save
    self.package.save(path_or_stream)
  File "D:\Program Files (x86)\python\lib\site-packages\docx\opc\package.py", line 172, in save
    PackageWriter.write(pkg_file, self.rels, self.parts)
  File "D:\Program Files (x86)\python\lib\site-packages\docx\opc\pkgwriter.py", line 32, in write
    phys_writer = PhysPkgWriter(pkg_file)
  File "D:\Program Files (x86)\python\lib\site-packages\docx\opc\phys_pkg.py", line 141, in __init__
    self._zipf = ZipFile(pkg_file, 'w', compression=ZIP_DEFLATED)
  File "D:\Program Files (x86)\python\lib\zipfile.py", line 1090, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '.\\大梧经济收入调查表表\\大梧村委会001温锡梅.docx'
